services:
  web:
    build: .
    command: -u app.py
    working_dir: /app
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:6
    ports:
      - "27017:27017"

  importer:
    build: .
    command: python import_csv.py
    working_dir: /app
    depends_on:
      - db
